[tool.poetry]
name = "Bootstrap-sampling-distribution"
version = "1.1.0"
description = "Using bootstrap to estimate the sampling distribution of a specific statistic."
authors = ["Elmo Moilanen"]

[tool.poetry.dependencies]
python = "^3.9"
numpy = "^1.20.0"
matplotlib = "^3.4.0"
scipy = "^1.6.0"

[tool.poetry.dev-dependencies]
black = "^21.5b2"
pytest = "^6.2.0"
flake8 = "^3.9.2"

[tool.black]
line-length = 100

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
