[tool.poetry]
name = "Bootstrap-sampling-distribution"
version = "1.2.0"
description = "Using bootstrap to estimate the sampling distribution of a specific statistic."
authors = ["Elmo Moilanen"]
license = "GPL-3.0-or-later"
keywords = ["statistics", "resampling", "sampling-distribution"]

[tool.poetry.dependencies]
python = "^3.9"
numpy = "^1.20"
matplotlib = "^3.4"
scipy = "^1.6"

[tool.poetry.dev-dependencies]
black = "21.12b0"
pytest = "^6.2"
flake8 = "^4.0"
pre-commit = "^2.16"

[tool.black]
line-length = 100
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
