[tool.poetry]
name = "Bootstrap-sampling-distribution"
version = "1.0.0"
description = "Use bootstrap resampling to estimate the sampling distribution of a statistic."
authors = ["Elmo Moilanen"]
license = "GPL-3.0-or-later"
keywords = ["statistics", "statistical-inference", "resampling", "sampling-distribution"]

[tool.poetry.dependencies]
python = ">=3.9,<3.11"
numpy = "^1.21"
matplotlib = "^3.5"
scipy = "^1.7"

[tool.poetry.dev-dependencies]
black = "^22.3"
pytest = "^7.1"
flake8 = "^4.0"
pre-commit = "^2.16"

[tool.black]
line-length = 100
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.venv
)/
'''

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
